baseURL = '/'
#languageCode = 'en-us'
theme = "etch"

ignoreFiles = ["/1/.*", "/2/.*" ]

[languages]
  [languages.en]
    title = ""
    languageName = "en"
    weight = 1
  [languages.gr]
    title = ""
    languageName = "gr"
    weight = 2

    [languages.fr]
    title = ""
    languageName = "FR"
    weight = 3


    [languages.jp]
    title = ""
    languageName = "JP"
    weight = 4


    [languages.kr]
    title = ""
    languageName = "KR"
    weight = 5

    [languages.de]
    title = ""
    languageName = "de"
    weight = 6


    [languages.pl]
    title = ""
    languageName = "pl"
    weight = 7

    [languages.nl]
    title = ""
    languageName = "nl"
    weight = 8

    [languages.it]
    title = ""
    languageName = "it"
    weight = 9

    [languages.es]
    title = ""
    languageName = "es"
    weight = 10 

